// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD-BekSvjCe81zXC0lZylX7WW-_gsi9s4',
    appId: '1:112237766772:web:54924695361279f00e0921',
    messagingSenderId: '112237766772',
    projectId: 'dog-shield',
    authDomain: 'dog-shield.firebaseapp.com',
    storageBucket: 'dog-shield.firebasestorage.app',
    measurementId: 'G-F2PW52SS1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Uy1guyt7FmNJG915mBtX9Cni7FY2MoM',
    appId: '1:112237766772:android:217e6da270520acc0e0921',
    messagingSenderId: '112237766772',
    projectId: 'dog-shield',
    storageBucket: 'dog-shield.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV69imrt6EZ1wvco4gIY59tQZYXUobV7o',
    appId: '1:112237766772:ios:fd6e74438c0f2a660e0921',
    messagingSenderId: '112237766772',
    projectId: 'dog-shield',
    storageBucket: 'dog-shield.firebasestorage.app',
    iosBundleId: 'com.example.dogshieldAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV69imrt6EZ1wvco4gIY59tQZYXUobV7o',
    appId: '1:112237766772:ios:fd6e74438c0f2a660e0921',
    messagingSenderId: '112237766772',
    projectId: 'dog-shield',
    storageBucket: 'dog-shield.firebasestorage.app',
    iosBundleId: 'com.example.dogshieldAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD-BekSvjCe81zXC0lZylX7WW-_gsi9s4',
    appId: '1:112237766772:web:d5eb541b41d935e00e0921',
    messagingSenderId: '112237766772',
    projectId: 'dog-shield',
    authDomain: 'dog-shield.firebaseapp.com',
    storageBucket: 'dog-shield.firebasestorage.app',
    measurementId: 'G-38STBSTQXF',
  );
}
