// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuJ9SnmaFJMYy46io6KmZdDUTBa3RbHLQ',
    appId: '1:14965472019:web:090a326e0e29ab2b9138e6',
    messagingSenderId: '14965472019',
    projectId: 'dogshield-dbeff',
    authDomain: 'dogshield-dbeff.firebaseapp.com',
    storageBucket: 'dogshield-dbeff.firebasestorage.app',
    measurementId: 'G-YWX0ERQDGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGrRLNRZ-CpSOirpWQh6-eScScYFoXGYI',
    appId: '1:14965472019:android:559d26f73521b2289138e6',
    messagingSenderId: '14965472019',
    projectId: 'dogshield-dbeff',
    storageBucket: 'dogshield-dbeff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm2tlNcBeChZioYscXPK7URyjPtW3KvKY',
    appId: '1:14965472019:ios:4984d6f452c3cdce9138e6',
    messagingSenderId: '14965472019',
    projectId: 'dogshield-dbeff',
    storageBucket: 'dogshield-dbeff.firebasestorage.app',
    iosBundleId: 'com.example.dogshieldAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm2tlNcBeChZioYscXPK7URyjPtW3KvKY',
    appId: '1:14965472019:ios:4984d6f452c3cdce9138e6',
    messagingSenderId: '14965472019',
    projectId: 'dogshield-dbeff',
    storageBucket: 'dogshield-dbeff.firebasestorage.app',
    iosBundleId: 'com.example.dogshieldAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuJ9SnmaFJMYy46io6KmZdDUTBa3RbHLQ',
    appId: '1:14965472019:web:93dd4d39779368f59138e6',
    messagingSenderId: '14965472019',
    projectId: 'dogshield-dbeff',
    authDomain: 'dogshield-dbeff.firebaseapp.com',
    storageBucket: 'dogshield-dbeff.firebasestorage.app',
    measurementId: 'G-VM20X069G5',
  );

}